import { Project } from "@/types/content";

export const projects: Project[] = [
  {
    id: "1",
    title: "Punky.AI",
    description:
      "Punky.AI is an AI-powered Discord bot designed to automate community moderation, support, and engagement. As a full-stack developer, I built both the backend REST API and the frontend dashboard from scratch. The backend is powered by TypeScript and Express.js, with a clean and scalable REST API architecture connected to MongoDB. I integrated OpenAI's APIs to deliver intelligent moderation and ticketing systems. On the frontend, I developed a fast and intuitive admin panel using React, Vite, and TailwindCSS. Every aspect of the project—from API routing and database design to the UX flow—was crafted with performance, reliability, and real user needs in mind. Punky.AI is not just a bot; it’s a robust platform engineered to scale with modern Discord communities.",
    image: "/assets/projects/punkyai.webp",
    tags: [
      "TypeScript",
      "Node.js",
      "Express.js",
      "REST API",
      "Discord.js",
      "MongoDB",
      "OpenAI",
      "React",
      "Vite",
      "Tailwind CSS",
      "Zod",
      "Docker",
      "PM2",
      "ESLint",
      "Prettier",
    ],
    category: "Discord Bot",
    liveUrl: "https://punky.ai/",
    slug: "punky-ai",
    featured: true,
    year: "2022 - 2025",
  },
  {
    id: "2",
    title: "Blucka",
    description:
      "Blucka is a Web3-native marketing agency focused on algorithmic growth, community development, and brand strategy for crypto projects. As a full-stack developer, I contributed to technical integrations, interactive modules, and content automation systems. My responsibilities included building and maintaining Discord bots, Telegram API integrations, and backend services that supported AI-powered content workflows. I also worked on automating Twitter (X) content pipelines tailored for engagement and algorithm performance. By combining creative strategy with scalable technical solutions, I helped shape Blucka’s platform to meet the fast-paced demands of Web3-native marketing.",
    image: "/assets/projects/blucka.webp",
    tags: [
      "Web3",
      "TypeScript",
      "Node.js",
      "React",
      "Telegram API",
      "Discord.js",
      "Tailwind CSS",
      "Next.js",
      "AI Integration",
      "OpenAI",
      "MongoDB",
      "REST API",
      "Content Automation",
    ],
    category: "Web3 Marketing",
    liveUrl: "https://blucka.com/",
    slug: "blucka",
    featured: true,
    year: "2023 - 2025",
  },
  {
    id: "3",
    title: "Mashoor",
    description:
      "Mashoor is a modern e-commerce platform where I work as a full-stack developer. The platform leverages cutting-edge technologies to deliver a seamless shopping experience with robust backend services and intuitive user interfaces. I contribute to both frontend and backend development, working with microservices architecture, cloud infrastructure, and modern web technologies to create scalable and performant solutions.",
    image: "/assets/projects/mashoor.webp",
    tags: [
      "Next.js",
      "TypeScript",
      "Java",
      "Spring Boot",
      "Tailwind CSS",
      "PostgreSQL",
      "AWS Lambda",
      "GraphQL",
      "REST API",
      "Full-Stack",
      "E-commerce",
      "Microservices",
      "Cloud Infrastructure",
    ],
    category: "E-commerce Platform",
    liveUrl: "https://mashoor.shop",
    slug: "mashoor",
    featured: true,
    year: "2025",
  },
  {
    id: "4",
    title: "Sponsorhub",
    description:
      "Sponsorhub is a modern web application that connects creators and sponsors. The frontend is built with Next.js and TypeScript, featuring smooth animations with Framer Motion. The backend is powered by Python and FastAPI, integrating various Meta APIs for advanced features. I developed the backend in Python and the frontend in TypeScript, ensuring a seamless, interactive user experience.",
    image: "/assets/projects/sponsorhub.webp",
    tags: [
      "Next.js",
      "TypeScript",
      "Framer Motion",
      "FastAPI",
      "Python",
      "Meta API",
      "Web Application",
      "Full-Stack",
      "Modern UI",
      "Animation",
    ],
    category: "Web Application",
    liveUrl: "https://sponsorhub.app/",
    slug: "sponsorhub",
    featured: true,
    year: "2025",
  },
  {
    id: "5",
    title: "Savaş Oto",
    description:
      "Savaş Oto was developed specifically for the electrical and automotive industries—by me, personally. I built a fast and robust infrastructure using powerful technologies like Next.js, TailwindCSS, Redis, Prisma, PostgreSQL, Docker, and PM2. Why did I do it this way? Because I built the site 😎 I wanted it to be a practical, high-performance platform worthy of the modern industrial world. The code, the design, the system architecture—every part of it went through my hands. In short, this project is a digital industrial website 'crafted by a true master.'",
    image: "/assets/projects/savas-oto.webp",
    tags: [
      "React",
      "Next.js",
      "Tailwind CSS",
      "Prisma",
      "PostgreSQL",
      "Redis",
      "Docker",
      "PM2",
      "Redux",
      "TypeScript",
      "Eslint",
      "Prettier",
    ],
    category: "Web Application",
    liveUrl: "https://savasoto.site/",
    slug: "savas-oto",
    featured: true,
    year: "2025",
  },
  {
    id: "6",
    title: "New Generation Library Herby",
    description:
      "I built an audio sharing platform with Nuxt, kind of like Blerp... But the code? Oh no, don’t even look at it! It’s basically a “how not to code” masterclass 😅",
    image: "/assets/projects/herby.webp",
    tags: [
      "Nuxt",
      "İyzico",
      "Tailwind CSS",
      "Pinia",
      "MongoDB",
      "Shadcn UI",
      "Vue",
      "TypeScript",
      "Express",
      "Socket.io",
    ],
    category: "Web Application",
    githubUrl: "https://github.com/Xjectro/herby-oldest",
    slug: "sound-sharing-platform",
    featured: true,
    year: "2024",
  },
  {
    id: "7",
    title: "Payload CMS Boilerplate",
    description:
      "A modern, production-ready boilerplate built with Payload CMS. This template provides a solid foundation for content management systems with modern web technologies, featuring a clean architecture and best practices for scalable CMS development.",
    image: "/assets/projects/payload-cms-boilerplate.webp",
    tags: [
      "payload cms",
      "typescript",
      "node.js",
      "cms",
      "boilerplate",
      "template",
      "content management",
      "headless cms",
      "modern stack",
      "mongodb",
      "express",
      "api",
      "backend",
      "full-stack",
      "production-ready",
    ],
    category: "CMS Template",
    githubUrl: "https://github.com/Xjectro/payload-cms-boilerplate",
    slug: "payload-cms-boilerplate",
    featured: true,
    year: "2025",
  },
  {
    id: "8",
    title: "Spring Boot GraphQL API",
    description:
      "Modern, scalable, and secure backend API template built with Spring Boot and GraphQL. This project demonstrates best practices for maintainable, extensible, and production-ready backend development.",
    image: "/assets/projects/spring-boot-graphql-api.webp",
    tags: [
      "java",
      "api",
      "graphql",
      "open-source",
      "template",
      "security",
      "jwt",
      "rest",
      "spring-boot",
      "scalable",
      "authentication",
      "microservice",
      "backend",
      "gradle",
      "example",
      "best-practices",
      "starter",
      "production-ready",
      "graphql-api",
      "ayered-architecture",
    ],
    category: "Web Application",
    githubUrl: "https://github.com/Xjectro/spring-boot-graphql-api",
    liveUrl: "http://localhost:8080",
    slug: "spring-boot-graphql-api",
    featured: true,
    year: "2025",
  },
  {
    id: "9",
    title: "Spring Boot GraphQL Advert Platform",
    description:
      "A Spring Boot-based web platform that allows users to create, manage, and query advertisements using GraphQL and JWT-based authentication.",
    image: "/assets/projects/spring-boot-graphql-advert-platform.webp",
    featured: true,
    year: "2025",
    githubUrl: "https://github.com/Xjectro/spring-boot-graphql-advert-platform",
    category: "Web Platform",
    liveUrl: "http://localhost:8080",
    slug: "spring-boot-graphql-advert-platform",
    tags: [
      "spring boot",
      "graphql",
      "advertisement",
      "jwt",
      "authentication",
      "java",
      "java 17",
      "graphql api",
      "spring security",
      "web platform",
      "rest alternative",
      "backend",
      "api",
      "h2 database",
      "html",
      "javascript",
      "crud",
    ],
  },
  {
    id: "10",
    title: "GraphQL Apollo Server",
    description:
      "A modern GraphQL API server built with Node.js, TypeScript, Apollo Server, and Prisma ORM. It features JWT authentication, role-based permissions, PostgreSQL database, Redis caching, and Docker containerization.",
    image: "/assets/projects/graphql-apollo-server.webp",
    featured: true,
    year: "2025",
    githubUrl: "https://github.com/Xjectro/graphql-apollo-server",
    category: "API Server",
    liveUrl: "http://localhost:4000",
    slug: "graphql-apollo-server",
    tags: [
      "node.js",
      "typescript",
      "apollo server",
      "graphql",
      "prisma",
      "postgresql",
      "redis",
      "docker",
      "jwt",
      "authentication",
      "authorization",
      "graphql directives",
      "service architecture",
      "graphql api",
      "backend",
      "api",
      "scalable",
      "caching",
    ],
  },
  {
    id: "11",
    title: "Deloyn",
    description:
      "Deloyn is a simple command-line tool to publish and deploy your project via SSH and SFTP under Node.",
    image: "/assets/projects/deloyn.webp",
    featured: true,
    year: "2025",
    githubUrl: "https://github.com/Xjectro/deloyn",
    category: "CLI Tool",
    liveUrl: "https://www.npmjs.com/package/deloyn",
    slug: "deloyn",
    tags: [
      "deloyn",
      "deploy",
      "ssh",
      "sftp",
      "cli",
      "nodejs",
      "command-line",
      "deployment",
      "automation",
      "file-transfer",
      "remote",
      "server",
      "script",
      "utility",
      "typescript",
      "javascript",
      "esbuild",
      "esbuild-register",
      "esbuild-plugin",
      "esbuild-plugin-typescript",
    ],
  },
  {
    id: "12",
    title: "Youtube Automation",
    description:
      "This project is a bot that automatically downloads memes from Reddit and uploads them as YouTube Shorts. 🚀",
    image: "/assets/projects/youtube-automation.webp",
    featured: true,
    year: "2025",
    githubUrl: "https://github.com/Xjectro/youtube-automation",
    category: "Automation",
    liveUrl: "https://www.youtube.com/@xjectro",
    slug: "youtube-automation",
    tags: [
      "python",
      "automation",
      "reddit",
      "youtube",
      "bot",
      "cli",
      "ffmpeg",
      "api",
      "video",
      "shorts",
      "upload",
      "script",
      "background",
      "server",
      "oauth2",
      "memes",
      "media",
      "cloud",
      "scheduler",
    ],
  },
  {
    id: "13",
    title: "Driving License Age Calculation",
    description:
      "A web application that helps users find out which driving license groups they are eligible for based on their country and date of birth. Supports multiple countries and provides eligibility breakdown by age group.",
    image: "/assets/projects/driving-license-age-calculation.webp",
    featured: true,
    year: "2025",
    category: "Web Application",
    liveUrl: "/apps/driving-license-age-calculation",
    slug: "driving-license-age-calculation",
    tags: [
      "typescript",
      "react",
      "nextjs",
      "tailwindcss",
      "webapp",
      "form",
      "calculator",
      "driving license",
      "age eligibility",
      "multi-language",
      "country support",
      "user-friendly",
      "responsive",
      "modern ui",
    ],
  },
  {
    id: "14",
    title: "Color Converter",
    description:
      "A web app to convert between OKLCH, HSL, HEX, and RGB color formats. Built with React, Next.js, and Tailwind CSS. Features instant conversion, color swatches, and a modern UI.",
    image: "/assets/projects/color-converter.webp",
    featured: true,
    year: "2025",
    category: "Web Application",
    liveUrl: "/apps/color-converter",
    slug: "color-converter",
    tags: [
      "react",
      "next.js",
      "tailwind css",
      "color conversion",
      "oklch",
      "hsl",
      "hex",
      "rgb",
      "typescript",
      "webapp",
      "modern ui",
    ],
  },
];

export const featuredProjects = projects.filter((project) => project.featured);
