export const workExperiences = [
  {
    id: "1",
    company: "Mashoor",
    position: "Full Stack Developer",
    duration: "June 2025 - Present",
    location: "Remote",
    description:
      "At Mashoor, I work as a full-stack developer on a modern e-commerce platform. I contribute to both frontend and backend development using cutting-edge technologies. The platform leverages microservices architecture with cloud infrastructure to deliver scalable and performant solutions. I work with GraphQL and REST APIs, implementing features across the entire technology stack.",
    technologies: [
      "Next.js",
      "TypeScript",
      "Java",
      "Spring Boot",
      "Tailwind CSS",
      "PostgreSQL",
      "AWS Lambda",
      "GraphQL",
      "REST API",
    ],
    relativeProjectId: "3",
    liveUrl: "https://mashoor.shop",
  },
  {
    id: "2",
    company: "Savaş Oto",
    position: "Full Stack Developer (Freelance)",
    duration: "2025",
    location: "Onsite / Freelance",
    description:
      "Savaş Oto is a high-performance digital platform developed for the automotive and electrical industries. I single-handedly built the entire system, from design to deployment. The project utilized modern web technologies like Next.js, TailwindCSS, Redis, PostgreSQL, and Prisma to ensure scalability and speed.",
    technologies: [
      "Next.js",
      "React",
      "Tailwind CSS",
      "Redis",
      "PostgreSQL",
      "Prisma",
      "Docker",
      "PM2",
    ],
    relativeProjectId: "4",
    liveUrl: "https://savasoto.site/",
  },
  {
    id: "3",
    company: "Blucka",
    position: "Full Stack Developer",
    duration: "July 2022 - May 2025",
    location: "Remote",
    description:
      "Blucka is a Web3-native marketing agency, where I worked on various technical integrations and automation systems. I developed and maintained backend services, Telegram and Discord bot integrations, and AI-driven content workflows. I also contributed to engagement-optimized Twitter automation pipelines and built full-stack applications using Next.js.",
    technologies: [
      "Next.js",
      "Node.js",
      "TypeScript",
      "React",
      "Telegram API",
      "Discord.js",
      "MongoDB",
      "OpenAI",
    ],
    relativeProjectId: "2",
    liveUrl: "https://blucka.com/",
    linkedinUrl: "https://www.linkedin.com/company/blucka",
  },
  {
    id: "4",
    company: "Punky.AI",
    position: "Full Stack Developer",
    duration: "May 2019 - July 2022",
    location: "Remote",
    description:
      "At Punky.AI, a subsidiary of Blucka, I worked as a full-stack developer responsible for building a Vue-based admin dashboard for a Discord bot. On the backend, I developed REST APIs using Express.js, with MongoDB and SQLite for data persistence. I played a key role in automating moderation and ticketing systems, and building scalable features tailored for Discord communities.",
    technologies: [
      "Vue.js",
      "Express.js",
      "MongoDB",
      "SQLite",
      "Discord.js",
      "REST API",
    ],
    relativeProjectId: "1",
    liveUrl: "https://punky.ai/",
  },
];
